# Generated by Django 4.1.5 on 2023-01-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
                ('food_price', models.IntegerField(default=0)),
                ('food_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
