# Generated by Django 4.1.5 on 2023-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resthotel',
            old_name='food_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='resthotel',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resthotel',
            old_name='food_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='resthotel',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
